apply plugin: 'com.android.application'

android {
    namespace 'com.personeltakip.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.personeltakip.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
